### ISSUE TITLE
Device Compatibility

### ISSUE THREAD

**Issue by jodale11** [fuzgirl1/GeekyMath#25]

**Comment by fuzgirl1** [comment]
So regarding this, I now have a total of four devices for us to use, each one a different size (even slightly) and each one is running a different version of Android. So now we can play around with these and see what we can do to fix this.

**Comment by fuzgirl1** [comment]
With this I've started researching different ways we could fix it. One way (this is at least the easiest way but it'll take some time) is we create format the page differently depending on screen size based off of [this](https://developer.android.com/training/basics/supporting-devices/screens.html). The other way (which I can't get a clue on how to do because other people want to do the same thing without any luck) is to add a vertical scroll bar, so if someone can find that, please help me look.

**Comment by fuzgirl1** [comment]
Okay so, I figured out the vertical scroll bar in learn. It looks like we are pretty much good on this now!
